### ISSUE TITLE
增加新库时如何本地调试?

### ISSUE THREAD

**Issue by atian25** [fis-components/components#10]

**Comment by atian25** [comment]
`node ./sync.js sync` 是全部库， 能否单个测试？

**Comment by 2betop** [comment]
node ./sync.js sync 实际上上是读取git commit 来决定更新哪些 components  的
1. 优先看 moudles/ 下有哪些文件变化了。
2. 如果没有文件变化，看 commit 的  message 是啥
   
   `update modules/**.js` glob 语法，如果目标 tag 不存在则创建。
   
   `forceupdate modules/**.js` 如果 目标 tag 存在，删了再创建。

**Comment by atian25** [comment]
不太明白，你指的是 `node .\sync.js foreupdate modules/zepto/**.js` ？

**Comment by 2betop** [comment]
我刚刚说了一堆废话！！！

我已经修改成可以你说的那样使用了

```
node sync.js sync modules/jquery.js
```

或者 

```
node sync.js sync modules/j*.js
```

**Comment by atian25** [comment]
```
nothing to commit, working directory clean
warning: LF will be replaced by CRLF in component.json.
The file will have its original line endings in your working directory.
remote: Anonymous access to fis-components/riot.git denied.
fatal: Authentication failed for 'https://github.com/fis-components/riot/'
Username for 'https://github.com':
```

本地调试的时候, 提交的这个逻辑是否需要干掉?

**Comment by atian25** [comment]
@2betop 还是存在问题， 除了上面说到的提交问题外， 还需要把你的git config改为local的。。。 否则我本地调试后， 我的其他项目就全变为你的签名了。

**Comment by 2betop** [comment]
Hello, 新增了调试程序，欢迎试用！

https://github.com/fis-components/components/blob/master/platform.md#%E6%9C%AC%E5%9C%B0%E6%B5%8B%E8%AF%95

**Comment by 2betop** [comment]
我觉得现在这个程序，基本满足调试需求了，先关了。
