### ISSUE TITLE
react 的 component.json 的 hook 属性消失了

### ISSUE THREAD

**Issue by GilbertSun** [fis-components/components#115]
为什么现在通过 fis install react@0.14.2 和 fis3 install react@0.14.2 里原先存在的 hook 属性消失了，所有的 addon 都不能通过这个机制正确的加载 react-with-addon.js 了

**Comment by GilbertSun** [comment]
![image](https://cloud.githubusercontent.com/assets/1615364/12387019/9e70461a-be04-11e5-9470-4b12dd8ee58c.png)

**Comment by 2betop** [comment]
我的错，我马上来修复下

**Comment by 2betop** [comment]
重新下载下，好了

**Comment by GilbertSun** [comment]
谢，赞效率
