### ISSUE TITLE
发现一个好东西 webpack 不知道它是怎么支持 npm bower 的组件的 建议大神们参考一下

### ISSUE THREAD

**Issue by cos800** [fis-components/components#12]
发现一个好东西 webpack
不知道它是怎么支持 npm bower 的组件的
建议大神们参考一下
省得一个个写转换规则

而且它的 require 可以自动查找。

**Comment by cos800** [comment]
http://hanjianwei.com/2014/09/10/webpack-package-manager-for-web/

**Comment by atian25** [comment]
其实我一直不太理解`browserify/webpack`这类全部打成一个JS文件的意义

**Comment by ascoders** [comment]
已直接支持 npm https://github.com/fex-team/fis3-hook-node_modules
