### ISSUE TITLE
对于clone耗时的组件，会不会影响fis-components的build CI?

### ISSUE THREAD

**Issue by codering** [fis-components/components#127]
比如 avalonjs( https://github.com/RubyLouvre/avalon)
我clone到本地都要好几分钟，网络不好可能更久。
把它纳入fis管理，不知道会不会有影响？

还有个问题，就是本地测试规则的时候，每次都是重新拉代码，可以优化下吗？

**Comment by codering** [comment]
@2betop  @andycall

**Comment by 2betop** [comment]
可以纳入，ci 是 travis 上跑（墙外），没有网络问题。

你说的本地测试是啥

**Comment by codering** [comment]
@2betop 就是执行 `node test.js modules/xxx.js` 时， 如果xxx对应的github项目过大，耗时很久。
可否加下缓存？ 多次执行是会快很多。
