### ISSUE TITLE
采用node_modules生态后，如何install满足mod规范的组件呢

### ISSUE THREAD

**Issue by fancyboynet** [fis-components/components#147]
原来只需要

```
fis3 install jquery

```

就可以引用components下的jquery了，很方便。
改用npm生态后加载某个mod组件具体要如何做呢？

**Comment by 2betop** [comment]
`npm install jquery`

然后 `require('jquery')` 就能用了。

唯一要变的是 fis-conf.js 

``` js
fis.unhook('components');
fis.hook('node_modules');
```

**Comment by 2betop** [comment]
npm 遵循的就是 commonjs 规范，所以，规范是没有变化的， mod.js 直接能用。

**Comment by fancyboynet** [comment]
赞
