### ISSUE TITLE
fis install fastclick 多了一个0文件

### ISSUE THREAD

**Issue by atian25** [fis-components/components#16]
![image](https://cloud.githubusercontent.com/assets/227713/6550419/2fd437e2-c662-11e4-8a2d-f9ec6f32275d.png)

btw, `fastclick.js` 缺少了 `README.md` 的转换

**Comment by atian25** [comment]
怀疑跟 #14 有关。

**Comment by 2betop** [comment]
之前那个 mapping 错误外加没有清空git 历史文件导致了这个问题。现在好了
