### ISSUE TITLE
通过 fis-components 同步过来的第三方组件源码不一致，导致无法正常使用

### ISSUE THREAD

**Issue by BelinChung** [fis-components/components#23]
在我添加的几个组件中，｀vue-validator｀  ｀vue` 的源码与源仓库源码不一致，导致无法使用

**Comment by BelinChung** [comment]
哦，原来是源里面release出的问题，哎

**Comment by 2betop** [comment]
我擦，我一会看看哈

**Comment by 2betop** [comment]
hi, 是会存在不一样，会哪些 umd 转成 commonJS 规范，但是这个不应该会导致无法正常使用。

**Comment by BelinChung** [comment]
后来发现不是 FIS 转的，我看 Vue 的 tag 里的 release 代码跟 master dist 里的代码不一致。
 https://github.com/yyx990803/vue/archive/0.11.5.zip
https://github.com/yyx990803/vue/blob/master/dist/vue.js
我不知道是不是他本身打包就出了问题？还是他那样写，FIS 不认

**Comment by 2betop** [comment]
可能你用的两个版本不一致导致的。

**Comment by BelinChung** [comment]
原谅下我，一早上折腾太多，脑袋太混乱了。
确实是 FIS 给转的，下图是 diff 
![qq20150409-3 2x](https://cloud.githubusercontent.com/assets/4954264/7061230/6e022340-dec1-11e4-8d41-949765e45f33.png)

在这行
`11  function (modules) {`
报 Uncaught SyntaxError: Unexpected token (

**Comment by 2betop** [comment]
哦，居然把一对括号搞没了

**Comment by 2betop** [comment]
hi, 是我的错，escodegen 在启用了 comments 后，这段解析就出问题了。现在应该可以了，要不你试试吧！

**Comment by BelinChung** [comment]
OK啦！
如果现在 FIS 支持大写的 components 的话，麻烦把我这个 fis-components/metisMenu 改成全大写或者全小写，我可以短路径引用，谢谢啦。

**Comment by 2betop** [comment]
你升级下 fis 就可以了

**Comment by 2betop** [comment]
`require('metisMenu')` 应该就能引用了
