### ISSUE TITLE
关于模块转换的时机

### ISSUE THREAD

**Issue by atian25** [fis-components/components#3]
`fis-components`和`scrat`的方案都是「自建库+`travis-ci`转换」。
总觉得不够完美，何时何人去触发新版本更新？

之前写了一个简单的install插件，思路是平台仅维护一套转换规则，安装时才转换。
缺点是还不够完善，且安装时才转换，会稍慢。

https://github.com/ng-workflow/ngfis-command-install

**Comment by 2betop** [comment]
目前 fis-components 是在 https://github.com/fis-components/components/tree/master/modules 中维护规则，规则一旦修改就会触发转换。

**Comment by atian25** [comment]
@2betop 谢谢，看了下， 转换规则那块写的很不错， 我研究下
