### ISSUE TITLE
如何自行封装component组件，不用官方推荐的方法

### ISSUE THREAD

**Issue by Zohner** [fis-components/components#35]
如果把其它组件封装成component组件，因为是自己的私有组件库，不知道怎么用 travis-ci，想自行修改代码封装，需要遵循什么规则，或者建私有库时怎么用 travis-ci

**Comment by 2betop** [comment]
travis-ci 其实就是执行了 `node sync.js`，如果你你没法用 travis-ci 那就想办法执行下那个程序，所有转换的逻辑都在里面。你可以先扫下逻辑。

**Comment by Zohner** [comment]
可以出一篇 component + travis-ci 组建私有库的教程么

**Comment by 2betop** [comment]
不支持  github 的私有仓库，要建私有平台，推荐用 gitlab

**Comment by 2betop** [comment]
另外，你为何要自己转换？自己组建私有平台你直接按规范存放就行。第三方的就直接走 fis-components。

**Comment by Zohner** [comment]
哦，说错，其实也不是私有仓库，应该叫企业仓库，想和 fis-components 区分开来，包括第三方的也统一放在企业仓库里，所以想把现有的 fis-components 搬过来，再添加其它内部的组件

**Comment by 2betop** [comment]
第三方的组建都统一走 fis-components，如果你复制过去，靠内部也维护不过来，毕竟现有的第三方组建太多了，目前 fis-components 里面也只整理了很小的一部分。这个就得靠所有的 fis 用户来一起维护的。所以我不会告诉你怎么弄过去的。

**Comment by Zohner** [comment]
额，其实第三方用 fis-components是同意的，确实没精力去维护，只不过想搬那套转换工具过来，这样自己添加组件时也是写一个配置文件就可以了，流程就和官方统一了，以后官方有改动这边也可以很快同步过来

**Comment by 2betop** [comment]
你要折腾的就是怎么集成 travis ci, 真么转换的代码都在这个仓库里面。fork过去就能用。

**Comment by Zohner** [comment]
好的，希望js模块化这一块官方可以补充多点文档，这样才有利于推广，这个 [demo](https://github.com/fex-team/fis-components-demo) 还是有疑惑的地方，比如生成的map_1f91365.js 是干啥用的，怎么合并js减少请求，等等
