### ISSUE TITLE
components 的多版本共存

### ISSUE THREAD

**Issue by nimoc** [fis-components/components#44]
> 因为所有依赖都会被打平安装在 components 目录下面，没有层级关系，如果出现同一组件被指定不同的版本将会出现冲突，目前的处理方案非常简单，没有做版本对比采用版本较高的版本，而是采用先入为主的原则处理。

如果项目中存在某些页面要用 jquery@1.11.2 某些页面需要用 jquery@2.1.4 时候如何做多版本共存？

**Comment by 2betop** [comment]
不能多版本共存，一个项目只能用一个版本。

**Comment by nimoc** [comment]
感谢回复， @2betop  平时有遇到过项目需要多版本共存的情况么？如果遇到都是如何处理的？

**Comment by ascoders** [comment]
fis生态采用使用最新版，处理方式是避免使用冲突版本，所以不建议版本共存。
想要共存请使用支持npm生态的插件
