### ISSUE TITLE
关于经过 browserify 后的第三方组件无法正常使用的问题

### ISSUE THREAD

**Issue by BelinChung** [fis-components/components#51]
类似的第三方组件，在 fis2 下修改后还能正常使用，但是 fis3 似乎却无法使用了，请问这个问题有没有临时的或者规范的解决办法呢？

**Comment by 2betop** [comment]
应该是包裹 amd 的区别，请换成 fis3-hook-commonjs

**Comment by BelinChung** [comment]
==== 更正下 ===
loader 应该跳过第三方组件内置的模块，不应该加入到 resourceMap 中
