### ISSUE TITLE
组件库能否出个像npm、spm、bower之类的独立站点

### ISSUE THREAD

**Issue by xuhuan** [fis-components/components#62]
RT，现在的组件量太少了。

**Comment by ascoders** [comment]
https://github.com/fis-components/components/blob/master/task.yml

给这个文件提pull request，可以将npm组件同步到fis，很方便

**Comment by xuhuan** [comment]
fis3 开始提供对npm的node_modules模块的支持，spm最新的也弃用了自己的spmjs.io，采用npm来管理包，能告诉下是为什么嘛？还有以后fis-components会不会被弃用，直接转入npm了？

**Comment by ascoders** [comment]
为了方便开发者呀，fis-components不会被弃用，npm只是另一种选择。

fis-components的配置文件和npm不一样，当然spm也和npm有一些区别，这导致了混用带来了一些麻烦，大部分社区组件需要从npm同步过来也导致了版本同步困难。

值得一提的是fis的components hook不能读取大部分npm的包，而对node_modules支持的版本使用了webpack读取方式才兼容了npm包，当然也可以继续通过 https://github.com/fis-components/components/blob/master/task.yml 这个地址将npm包转换过来。
