### ISSUE TITLE
使用GitLab组件私有组件库时候，如何指定GitLab域名？

### ISSUE THREAD

**Issue by wizcabbit** [fis-components/components#7]
引用私有GitLab地址的时候，如何在dep里面指定GitLab的域名？

components路径说明里面这句：

github:fis-components/jquery@1.9.1
gitlap:fis-components/jquery@1.9.1
lights:lightjs.duapp.com/jquery@1.9.1

显然没有指定gitlab的域名

**Comment by 2betop** [comment]
目前，只支持百度内部的 gitlab 不支持指定外部地址！

**Comment by 2betop** [comment]
目前 lights 是可以指定域名的！

**Comment by wizcabbit** [comment]
@2betop got it~
是否有支持外部gitlab的计划？如果有的话对组件生态的建立会有很大帮助

**Comment by 2betop** [comment]
可以支持，我回头琢磨下！手头下有其他事情，先放放！

**Comment by wizcabbit** [comment]
thanks~ ^_^

**Comment by 2betop** [comment]
hi， 发布了一个新版本，只能批量的指定 gitlab 域名，不能同时使用多个 gitlab 域名下面的仓库。

有两种方式指定:

方式一  component.json 文件里面

``` json
{
   "gitlab": {
        "domain": "http://gitlab.your-domain.io/"
   }
}
```

方式二  fis-conf.js

``` js
fis.config.set('component.gitlab', {
    domain: 'http://gitlab.your-domain.io/'
});
```

**Comment by 2betop** [comment]
如果自己搭建 gitlab  注意指定 domain 外，还记得要指定帐号 token 在 gitlab 用户资料里面找找。

**Comment by atian25** [comment]
更新到components的readme吧

**Comment by wizcabbit** [comment]
赞效率诶，周末试试！！

**Comment by wizcabbit** [comment]
内部GitLab和fis都搭建完成，从fis-components里导入了一个示例库，但是在fis install后会提示
analyzing dependencies | 
[ERROR] undefined undefined while loading gitlab:http://XXXXX/js-components/jquery
有可能是什么原因么？
btw “指定账号token”，我可以在gitlab里建application token，可是建给谁呢…
great thx

**Comment by 2betop** [comment]
fis.config.set('component.gitlab.token', 'xxxxxx');

**Comment by 2betop** [comment]
你看下个人信息里面，不用建 applicaiton token，个人帐号里面就有个 token

**Comment by wizcabbit** [comment]
token已经设置好了~ 可是错误信息依旧…
是fis install报出来的么？我在试着debug…

**Comment by 2betop** [comment]
lib/remote/gitlab.js 里面。看看是不是哪个请求 404 了

**Comment by 2betop** [comment]
@wizcabbit 是我的错误，犯二了。https://github.com/fex-team/fis-command-install/commit/6a740e3a70a013d2a7e902eb90c7e1f435fbf5b6

已修复！

**Comment by wizcabbit** [comment]
wonderful啊！！！正经郁闷了几天~
