### ISSUE TITLE
fis install antd. [ERROR] Invalid Version?

### ISSUE THREAD

**Issue by L-x-C** [fis-components/components#71]
`[ERROR] Invalid Version: b892eb2bf103c49173de7092be2ad9858c5704a5`

其他都正常

**Comment by 2betop** [comment]
运行时报错，还是安装期？

**Comment by L-x-C** [comment]
安装

**Comment by L-x-C** [comment]
安装别的都是好的

**Comment by 2betop** [comment]
不应该吧，我这除了会出现 从 mirror 下载出错的提示，是能正常安装下来的。

**Comment by L-x-C** [comment]
好了...
我用fis3 install antd好了.....

**Comment by L-x-C** [comment]
closed #71
