### ISSUE TITLE
fis install 路径寻找问题

### ISSUE THREAD

**Issue by 303182519** [fis-components/components#8]

**Comment by 303182519** [comment]
# fis install github:xxx/jquery

是不是先判断本地有没有jquery，假如没有然后去fis-components这里找，找不到再去xxx是这样的寻找路径吗

**Comment by 2betop** [comment]
是的，本地要是版本不符也会去下载

**Comment by 2betop** [comment]
这里有详情：https://github.com/fis-components/components/blob/master/install.md#%E5%AE%89%E8%A3%85%E8%AF%B4%E6%98%8E
