### ISSUE TITLE
组件依赖的写法能改成通用的写法吗？方便安装其他类型的包

### ISSUE THREAD

**Issue by asoiso** [fis-components/components#9]
"dependencies": [
"jquery@>=1.6"
]

"dependencies": {
"jquery": ">=1.6"
},

**Comment by 2betop** [comment]
什么叫通用写法？你是说是对象而不是数组？目前两种写法都支持！

**Comment by asoiso** [comment]
jquery@>=1.6 这种依赖写法， bower、component、duo都分析不了这种写法，而fis-components组件库里基本上都是这种写法，不能公用其他的包管理器。

**Comment by 2betop** [comment]
不能公用 bower、component、duo 因为要在 fis 里面用，需要一定的规范。所以 fis 里面都是使用处理过后的 component 放在 fis-components 机构里面。

**Comment by asoiso** [comment]
scrat同样是基于fis内核去开发的，它的生态模块就是遵循component规范的，fis install能安装并且使用scrat-team的生态模块，scrat不能安装fis-components的生态模块，我觉得这是问题所在。

**Comment by 2betop** [comment]
fis-component 是兼容 component 用法。当时没有采用 component 规范主要是考虑到可能白名单不能满足我移动资源的需求。比如 /dist/xxx.js 我希望安装后是 /xxx.js，component 规范里面只会通过白名单指定我有那些资源，安装的时候保留路径放在 /components 目录。

**Comment by 2betop** [comment]
但是呢，现在资源移动在转换期就做了，可以考虑下采用 component 规范。但是跟 bower 可能是有很大的区别， bower 是黑名单

**Comment by asoiso** [comment]
给力～！

**Comment by atian25** [comment]
> scrat不能安装fis-components的生态模块，我觉得这是问题所在

这个可以 @fouber , `scrat`的`install`是定制化的, `fis-components`出来比较晚

**Comment by atian25** [comment]
@2betop 现在的`fis install`似乎不支持这格式， 是bug吗？

```
"dependencies": {
   "jquery": ">=1.6"
},
```

提示：
`[WARNI] Installed nothing!`

**Comment by 2betop** [comment]
重装下 fis 吧！

**Comment by atian25** [comment]
fis install --save 会支持2种格式吗?

**Comment by atian25** [comment]
刚验证了, 可以.

**Comment by atian25** [comment]
刚验证了， 如果写第2种， fis install --save 后会自动转为第一种。。。

**Comment by 2betop** [comment]
恩，纠结呢，现在看来，默认用第二种也未尝不可！

**Comment by atian25** [comment]
建议采用大众化的规范。

"zepto": "github:fis-components/zepto@v1.1.4"
